version: '3'

services:
  db:
    platform: linux/x86_64
    image: postgres:12-alpine
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      app_net:
        ipv4_address: '172.20.0.2'

  backend:
    container_name: backend
    build: ./backend/
    image: backend
    env_file: ./.env
    command: bundle exec rails server -b 0.0.0.0
    tty: true
    stdin_open: true
    volumes:
      - ./backend:/app:cached
      - /app/vendor
      - /app/tmp
      - /app/log
      - /app/.git
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - db
    ports:
      - ${BACKEND_PORT:-5000}:3000
    networks:
      app_net:
        ipv4_address: '172.20.0.3'

  frontend:
    container_name: front
    build: ./frontend/
    image: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - ${FRONTEND_PORT:-3000}:3000
    command: yarn dev
    tty: true
    stdin_open: true
    networks:
      app_net:
        ipv4_address: '172.20.0.4'

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24

volumes:
  db_data:
